/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   pouchdb-quick-search.html
 */

/// <reference path="../pouchdb-quick-search/dist/pouchdb.quick-search.d.ts" />

